spring:
  application:
    name: attornatus-backend
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    default-schema: attornatus
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
  h2:
    console:
      enabled: true

server:
  port: 3000
  servlet:
    context-path: /api




